### ISSUE TITLE
Unable to use it in angular-5

### ISSUE THREAD

**Issue by mayank12psingh** [ajay-gandhi/textbelt#4]
Hello,
I am trying to implement this in my angular-5 project to send sms on click of a button but it's not working.
Facing error :- Cannot find name 'require'.

**Comment by ajay-gandhi** [comment]
Hey,

This is a Node.js module, it isn't supported / won't run in the browser. The module needs the ability to run shell commands, so it would need some nontrivial modifications to run in the browser.
